export const poster = (path) => `https://image.tmdb.org/t/p/w500${path}`;

export const seedFilms = [
  {
    id: "past-lives",
    title: "Past Lives",
    year: 2023,
    director: "Celine Song",
    genre: "Romance · Drama",
    runtime: 106,
    image: "/k3waqVXSnvCZWfJYNtdamTgTtTA.jpg",
    color: "#48645a",
    rating: 4.5,
    watched: "2026-09-12",
    mood: "Quietly moved",
    favorite: false,
    review:
      "Some people are a place you can never quite return to.\n\nI keep thinking about the silence at the end. How a film can hold so much in the space between two people. Beautiful, gentle, and quietly devastating.",
    status: "watched",
  },
  {
    id: "interstellar",
    title: "Interstellar",
    year: 2014,
    director: "Christopher Nolan",
    genre: "Sci-fi · Adventure",
    runtime: 169,
    image: "/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg",
    color: "#8a9699",
    rating: 5,
    watched: "2026-09-09",
    mood: "In awe",
    favorite: true,
    review:
      "A reminder that the biggest stories are really about the smallest things. A father. A daughter. A promise to come home.\n\nThe docking scene still makes me forget to breathe. Watched with the lights off and the sound turned all the way up. The only way.",
    status: "watched",
  },
  {
    id: "grand-budapest",
    title: "The Grand Budapest Hotel",
    year: 2014,
    director: "Wes Anderson",
    genre: "Comedy · Adventure",
    runtime: 100,
    image: "/eWdyYQreja6JGCzqHWXpWHDrrPo.jpg",
    color: "#b5757f",
    rating: 4.5,
    watched: "2026-09-06",
    mood: "Delightfully lost",
    favorite: true,
    review:
      "Like opening a beautiful, slightly battered storybook someone left on a train.\n\nEvery frame is a little world I want to live inside. Underneath all the pink and pastry is something so tender about friendship, and the things we try to preserve as the world changes around us.\n\nA perfect rainy Sunday film. With a very good slice of cake.",
    status: "watched",
  },
  {
    id: "la-la-land",
    title: "La La Land",
    year: 2016,
    director: "Damien Chazelle",
    genre: "Musical · Romance",
    runtime: 128,
    image: "/uDO8zWDhfWwoFdKS4fzkUJt0Rf0.jpg",
    color: "#3b4693",
    rating: 4,
    watched: "2026-08-30",
    mood: "Bittersweet",
    favorite: false,
    review:
      "Here’s to the ones who dream.\n\nThat last look across the room says everything. I love how this film lets joy and heartbreak exist in the same frame. Spent the rest of the evening listening to the soundtrack.",
    status: "watched",
  },
  {
    id: "perfect-days",
    title: "Perfect Days",
    year: 2023,
    director: "Wim Wenders",
    genre: "Drama",
    runtime: 124,
    image: "/tvUHVSTJV9ITON3oyHaWp7oaAc8.jpg",
    color: "#527483",
    rating: 5,
    watched: "2026-08-24",
    mood: "At peace",
    favorite: true,
    review:
      "Today is today. Tomorrow is tomorrow.\n\nAn invitation to pay attention. To the light in the trees, to a familiar song, to the small rituals that make up a life. Went for a long walk afterwards. Left my phone at home.",
    status: "watched",
  },
  {
    id: "dune",
    title: "Dune",
    year: 2021,
    director: "Denis Villeneuve",
    genre: "Sci-fi · Adventure",
    runtime: 155,
    image: "/d5NXSklXo0qyIYkgV94XAgMIckC.jpg",
    color: "#9a7955",
    rating: 4.5,
    watched: "2026-08-18",
    mood: "In awe",
    favorite: false,
    review:
      "The scale of it. The sound of it. A world that feels impossibly ancient and completely new. This is why we go to the cinema.",
    status: "watched",
  },
  {
    id: "whiplash",
    title: "Whiplash",
    year: 2014,
    director: "Damien Chazelle",
    genre: "Drama · Music",
    runtime: 107,
    image: "/7fn624j5lj3xTme2SgiLCeuedmO.jpg",
    color: "#997b43",
    rating: 4.5,
    watched: "2025-11-22",
    mood: "On the edge of my seat",
    favorite: false,
    review:
      "I don’t think I relaxed a single muscle for the last twenty minutes.\n\nA film about rhythm that feels like a held breath. Still not sure whether that final smile is a victory or a surrender.",
    status: "watched",
  },
  {
    id: "arrival",
    title: "Arrival",
    year: 2016,
    director: "Denis Villeneuve",
    genre: "Sci-fi · Drama",
    runtime: 116,
    image: "/pEzNVQfdzYDzVK0XqxERIw2x2se.jpg",
    color: "#697570",
    rating: 5,
    watched: "2025-04-17",
    mood: "Quietly moved",
    favorite: true,
    review:
      "What if you knew the whole story before it began?\n\nCame for a film about visitors from another world. Left thinking about the people in mine. There’s a particular kind of courage in choosing something beautiful, even knowing it won’t last.",
    status: "watched",
  },
  {
    id: "her",
    title: "Her",
    year: 2013,
    director: "Spike Jonze",
    genre: "Romance · Sci-fi",
    runtime: 126,
    image: "/eCOtqtfvn7mxGl6nfmq4b1exJRc.jpg",
    color: "#a84843",
    rating: 4.5,
    watched: "2024-12-08",
    mood: "Bittersweet",
    favorite: false,
    review:
      "So much warmth in a story about loneliness.\n\nThe city, the colors, the conversations that drift through an ordinary day. It made me want to write someone an actual letter.",
    status: "watched",
  },
  {
    id: "amelie",
    title: "Amélie",
    year: 2001,
    director: "Jean-Pierre Jeunet",
    genre: "Romance · Comedy",
    runtime: 122,
    image: "/nSxDa3M9aMvGVLoItzWTepQ5h5d.jpg",
    color: "#587c43",
    rating: 4.5,
    watched: "2024-03-21",
    mood: "Delightfully lost",
    favorite: false,
    review:
      "A collection of tiny kindnesses, wrapped in the green and gold of Paris.\n\nSometimes a movie reminds you to be a little more curious about the people you pass every day. This was one of those evenings.",
    status: "watched",
  },
  {
    id: "before-sunrise",
    title: "Before Sunrise",
    year: 1995,
    director: "Richard Linklater",
    genre: "Romance · Drama",
    runtime: 101,
    image: "/kf1Jb1c2JAOqjuzA3H4oDM263uB.jpg",
    color: "#897454",
    rating: 5,
    watched: "2023-07-09",
    mood: "Inspired",
    favorite: true,
    review:
      "Just two people walking and talking. Somehow, an entire universe.\n\nWatched on a summer night with the windows open. Afterwards, the street outside felt full of possibilities.",
    status: "watched",
  },
  {
    id: "lost-in-translation",
    title: "Lost in Translation",
    year: 2003,
    director: "Sofia Coppola",
    genre: "Drama · Romance",
    runtime: 102,
    image: "/3jCLmYDIIiSMPujbwygNpqdpM8N.jpg",
    color: "#625c76",
    rating: 4,
    watched: "2023-01-14",
    mood: "Bittersweet",
    favorite: false,
    review:
      "That feeling of being far from home, even when you aren’t sure where home is.\n\nThe quiet hotel bar, the neon, the strange comfort of being understood by a stranger. I’m glad we never hear the whisper.",
    status: "watched",
  },
  {
    id: "moonrise-kingdom",
    title: "Moonrise Kingdom",
    year: 2012,
    director: "Wes Anderson",
    genre: "Comedy · Romance",
    runtime: 94,
    image: "/wOgmhrSUwOuZJsQXf2GsI923N0f.jpg",
    color: "#a59862",
    rating: 0,
    watched: "",
    mood: "",
    favorite: false,
    review: "",
    status: "watchlist",
  },
  {
    id: "spirited-away",
    title: "Spirited Away",
    year: 2001,
    director: "Hayao Miyazaki",
    genre: "Animation · Fantasy",
    runtime: 125,
    image: "/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg",
    color: "#497a70",
    rating: 0,
    watched: "",
    mood: "",
    favorite: false,
    review: "",
    status: "watchlist",
  },
];

export const moods = [
  "Quietly moved",
  "In awe",
  "Delightfully lost",
  "Bittersweet",
  "At peace",
  "Inspired",
  "Underwhelmed",
  "On the edge of my seat",
];
